In [1]:
import numpy as np
import pandas as pd
#from sklearn import preprocessing
import matplotlib.pyplot as plt
import seaborn as sns
#from IPython.core.debugger import Tracer
#import scipy as sp

from pylab import rcParams
rcParams['figure.figsize'] = 5, 8

%matplotlib inline

# Exercise One

In [66]:
y = np.array([2,3,0,-1])
x = np.array([4,-2,1,
              5,-3,2,
              1,1,3,
              0,1,4]).reshape(4,3)
lam = 1
beta = np.zeros(3)

In [67]:
x

array([[ 4, -2,  1],
       [ 5, -3,  2],
       [ 1,  1,  3],
       [ 0,  1,  4]])

In [68]:
x[:,0:3]

array([[ 4, -2,  1],
       [ 5, -3,  2],
       [ 1,  1,  3],
       [ 0,  1,  4]])

In [69]:
x[:, (0,2)]

array([[4, 1],
       [5, 2],
       [1, 3],
       [0, 4]])

In [70]:
x[:, (0,1,2)]

array([[ 4, -2,  1],
       [ 5, -3,  2],
       [ 1,  1,  3],
       [ 0,  1,  4]])

In [71]:
x[:, [0,2]]

array([[4, 1],
       [5, 2],
       [1, 3],
       [0, 4]])

In [72]:
x[:, np.arange(x.shape[1])]

array([[ 4, -2,  1],
       [ 5, -3,  2],
       [ 1,  1,  3],
       [ 0,  1,  4]])

In [73]:
x.shape[1]

3

In [74]:
idxs = list(range(x.shape[1]))
idxs.remove(0)
x[:, idxs]

array([[-2,  1],
       [-3,  2],
       [ 1,  3],
       [ 1,  4]])

In [75]:
x[:, foo]

array([[4, 1],
       [5, 2],
       [1, 3],
       [0, 4]])

In [76]:
beta

array([ 0.,  0.,  0.])

In [77]:
beta[idxs]

array([ 0.,  0.])

In [78]:
np.arange(3)[idxs]

array([1, 2])

In [79]:
foox = x[:, (1,2)]
foox

array([[-2,  1],
       [-3,  2],
       [ 1,  3],
       [ 1,  4]])

In [80]:
foobeta = beta[[1,2]]
foobeta

array([ 0.,  0.])

In [81]:
foox.dot(foobeta)

array([ 0.,  0.,  0.,  0.])

In [82]:
y

array([ 2,  3,  0, -1])

In [83]:
y - foox.dot(foobeta)

array([ 2.,  3.,  0., -1.])

In [85]:
x[:,0]

array([4, 5, 1, 0])

In [86]:
x[:,0] * y - foox.dot(foobeta)

array([  8.,  15.,   0.,   0.])

In [87]:
sum(x[:,0] * y - foox.dot(foobeta))

23.0

In [88]:
2 * sum(x[:,0] * y - foox.dot(foobeta))

46.0

In [89]:
.536*4 + 0*1

2.144

In [90]:
.536*5

2.68

In [91]:
.536*1

0.536

In [92]:
3-2.68

0.31999999999999984

In [93]:
-2*-.144

0.288

In [94]:
-3*.32

-0.96

In [95]:
.288-0.96-0.536-1

-2.208

In [96]:
-2.208*2

-4.416

In [98]:
foo_x_minus = x[:, [0,2]]
foo_x_minus

array([[4, 1],
       [5, 2],
       [1, 3],
       [0, 4]])

In [99]:
foo_beta_minus = np.array([0.536, 0])
foo_beta_minus

array([ 0.536,  0.   ])

In [101]:
2 * sum(x[:, 0] * y - foo_x_minus.dot(foo_beta_minus))

35.280000000000001

In [102]:
foo_x_minus.dot(foo_beta_minus)

array([ 2.144,  2.68 ,  0.536,  0.   ])

In [104]:
y - foo_x_minus.dot(foo_beta_minus)

array([-0.144,  0.32 , -0.536, -1.   ])

In [105]:
2 * sum(x[:, 1] * y - foo_x_minus.dot(foo_beta_minus))

-38.719999999999999

In [107]:
y - foo_x_minus.dot(foo_beta_minus)

array([-0.144,  0.32 , -0.536, -1.   ])

In [109]:
x[:, 1]

array([-2, -3,  1,  1])

In [112]:
x[:, 1] * (y - foo_x_minus.dot(foo_beta_minus))

array([ 0.288, -0.96 , -0.536, -1.   ])

In [113]:
2 * sum(x[:, 1] * (y - foo_x_minus.dot(foo_beta_minus)))

-4.4159999999999986

In [115]:
x[:, 0]

array([4, 5, 1, 0])

In [116]:
x[:, 0]**2

array([16, 25,  1,  0])

In [117]:
2 * sum(x[:, 1]**2)

30

In [120]:
(-4.4159999999999986 + 1) / 30

-0.11386666666666662

In [121]:
from coorddescent import *

In [128]:
c_term(beta, x, y, 3, 10)

8.0