In [197]:
import numpy as np
import pandas as pd
#from sklearn import preprocessing
import matplotlib.pyplot as plt
import seaborn as sns
#from IPython.core.debugger import Tracer
#import scipy as sp

from pylab import rcParams
rcParams['figure.figsize'] = 5, 8

%matplotlib inline

# Exercise One

In [198]:
y = np.array([2,3,0,-1])
x = np.array([4,-2,1,
              5,-3,2,
              1,1,3,
              0,1,4]).reshape(4,3)
lam = 1
beta = np.zeros(3)

In [199]:
x

array([[ 4, -2,  1],
       [ 5, -3,  2],
       [ 1,  1,  3],
       [ 0,  1,  4]])

In [200]:
x[:,0:3]

array([[ 4, -2,  1],
       [ 5, -3,  2],
       [ 1,  1,  3],
       [ 0,  1,  4]])

In [201]:
x[:, (0,2)]

array([[4, 1],
       [5, 2],
       [1, 3],
       [0, 4]])

In [202]:
x[:, (0,1,2)]

array([[ 4, -2,  1],
       [ 5, -3,  2],
       [ 1,  1,  3],
       [ 0,  1,  4]])

In [203]:
x[:, [0,2]]

array([[4, 1],
       [5, 2],
       [1, 3],
       [0, 4]])

In [204]:
x[:, np.arange(x.shape[1])]

array([[ 4, -2,  1],
       [ 5, -3,  2],
       [ 1,  1,  3],
       [ 0,  1,  4]])

In [205]:
x.shape[1]

3

In [206]:
idxs = list(range(x.shape[1]))
idxs.remove(0)
x[:, idxs]

array([[-2,  1],
       [-3,  2],
       [ 1,  3],
       [ 1,  4]])

In [207]:
x[:, foo]

array([[4, 1],
       [5, 2],
       [1, 3],
       [0, 4]])

In [208]:
beta

array([ 0.,  0.,  0.])

In [209]:
beta[idxs]

array([ 0.,  0.])

In [210]:
np.arange(3)[idxs]

array([1, 2])

In [211]:
foox = x[:, (1,2)]
foox

array([[-2,  1],
       [-3,  2],
       [ 1,  3],
       [ 1,  4]])

In [212]:
foobeta = beta[[1,2]]
foobeta

array([ 0.,  0.])

In [213]:
foox.dot(foobeta)

array([ 0.,  0.,  0.,  0.])

In [214]:
y

array([ 2,  3,  0, -1])

In [215]:
y - foox.dot(foobeta)

array([ 2.,  3.,  0., -1.])

In [216]:
x[:,0]

array([4, 5, 1, 0])

In [217]:
x[:,0] * y - foox.dot(foobeta)

array([  8.,  15.,   0.,   0.])

In [218]:
sum(x[:,0] * y - foox.dot(foobeta))

23.0

In [219]:
2 * sum(x[:,0] * y - foox.dot(foobeta))

46.0

In [220]:
.536*4 + 0*1

2.144

In [221]:
.536*5

2.68

In [222]:
.536*1

0.536

In [223]:
3-2.68

0.31999999999999984

In [224]:
-2*-.144

0.288

In [225]:
-3*.32

-0.96

In [226]:
.288-0.96-0.536-1

-2.208

In [227]:
-2.208*2

-4.416

In [228]:
foo_x_minus = x[:, [0,2]]
foo_x_minus

array([[4, 1],
       [5, 2],
       [1, 3],
       [0, 4]])

In [229]:
foo_beta_minus = np.array([0.536, 0])
foo_beta_minus

array([ 0.536,  0.   ])

In [230]:
2 * sum(x[:, 0] * y - foo_x_minus.dot(foo_beta_minus))

35.280000000000001

In [231]:
foo_x_minus.dot(foo_beta_minus)

array([ 2.144,  2.68 ,  0.536,  0.   ])

In [232]:
y - foo_x_minus.dot(foo_beta_minus)

array([-0.144,  0.32 , -0.536, -1.   ])

In [233]:
2 * sum(x[:, 1] * y - foo_x_minus.dot(foo_beta_minus))

-38.719999999999999

In [234]:
y - foo_x_minus.dot(foo_beta_minus)

array([-0.144,  0.32 , -0.536, -1.   ])

In [235]:
x[:, 1]

array([-2, -3,  1,  1])

In [236]:
x[:, 1] * (y - foo_x_minus.dot(foo_beta_minus))

array([ 0.288, -0.96 , -0.536, -1.   ])

In [237]:
2 * sum(x[:, 1] * (y - foo_x_minus.dot(foo_beta_minus)))

-4.4159999999999986

In [238]:
x[:, 0]

array([4, 5, 1, 0])

In [239]:
x[:, 0]**2

array([16, 25,  1,  0])

In [240]:
2 * sum(x[:, 1]**2)

30

In [241]:
(-4.4159999999999986 + 1) / 30

-0.11386666666666662

In [242]:
from coorddescent import *

In [243]:
get_sequence_of_js(3,3)

NameError: name 'get_sequence_of_js' is not defined

In [244]:
c_term(beta, x, y, 3, 10)

8.0

In [245]:
minimize_beta_term(beta, x, y, 1, lam)

0.5357142857142857

In [246]:
minimize_beta_term(np.array([0.5357142857142857, 0, 0]), x, y, 2, lam)

-0.11428571428571432

In [247]:
minimize_beta_term(np.array([0.5357142857142857, 
                             -0.11428571428571432, 0]), x, y, 3, lam)

-0.15738095238095237

In [248]:
minimize_beta_term(np.array([0.5357142857142857, 
                             -0.11428571428571432, 
                             -0.15738095238095237]), x, y, 1, lam)

0.53955215419501124

In [249]:
minimize_beta_term(np.array([0.53955215419501124, 
                             -0.11428571428571432, 
                             -0.15738095238095237]), x, y, 2, lam)

-0.11914890400604702

In [250]:
minimize_beta_term(np.array([0.53955215419501124, 
                             -0.11914890400604702, 
                             -0.15738095238095237]), x, y, 3, lam)

-0.15971785084404125

In [251]:
x.shape[1]

3

In [254]:
y

array([ 2,  3,  0, -1])

In [255]:
np.array(y)

array([ 2,  3,  0, -1])

In [150]:
np.ravel(y)

array([ 2,  3,  0, -1])

In [155]:
y[np.newaxis]

array([[ 2,  3,  0, -1]])

In [170]:
np.repeat(y[np.newaxis], 2, 0).flatten()

array([ 2,  3,  0, -1,  2,  3,  0, -1])

In [158]:
y[np.newaxis]

array([[ 2,  3,  0, -1]])

In [171]:
np.repeat(np.arange(3)[np.newaxis], 2, 0).flatten()

array([0, 1, 2, 0, 1, 2])

In [172]:
np.repeat(np.arange(x.shape[1])[np.newaxis], 2, 0).flatten()

array([0, 1, 2, 0, 1, 2])

In [173]:
np.repeat(np.arange(x.shape[1])[np.newaxis], 10, 0).flatten()

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2])

In [174]:
max_iter = 10

In [175]:
max_iter / x.shape[1]

3.3333333333333335

In [177]:
np.repeat(np.arange(x.shape[1])[np.newaxis], 3, 0).flatten()

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [179]:
for i in range(3):
    print(i)

0
1
2


In [182]:
np.arange(1,4)

array([1, 2, 3])

In [183]:
?np.repeat

In [186]:
np.append(np.arange(1,4), np.arange(1,4))

array([1, 2, 3, 1, 2, 3])

In [283]:
beta_new = np.array([.5, .2, -.3])
beta_new

array([ 0.5,  0.2, -0.3])

In [284]:
sum(abs(beta_new))

1.0

In [274]:
np.random.choice(np.arange(1,4), 10)

array([3, 3, 3, 2, 1, 1, 3, 2, 3, 3])

In [289]:
y

array([ 2,  3,  0, -1])

In [286]:
beta

array([ 0.,  0.,  0.])

In [288]:
y - x.dot(beta)

array([ 2.,  3.,  0., -1.])

In [290]:
(y - x.dot(beta))**2

array([ 4.,  9.,  0.,  1.])

In [293]:
sum(y - x.dot(beta))**2

16.0

In [301]:
(1/len(x)) * sum( (y - x.dot(beta))**2 ) 

3.5

In [299]:
(1 / len(x)) * sum((y - x.dot(beta))**2) 

3.5

In [303]:
(y - x.dot(beta))**2

array([ 4.,  9.,  0.,  1.])

3.5

In [309]:
beta_new = np.array([1,2,3])
beta_new

array([1, 2, 3])

In [310]:
y

array([ 2,  3,  0, -1])

In [311]:
x

array([[ 4, -2,  1],
       [ 5, -3,  2],
       [ 1,  1,  3],
       [ 0,  1,  4]])

In [312]:
x.dot(beta_new)

array([ 3,  5, 12, 14])

In [313]:
y - x.dot(beta_new)

array([ -1,  -2, -12, -15])

In [314]:
(y - x.dot(beta_new))**2

array([  1,   4, 144, 225])

In [316]:
sum((y - x.dot(beta_new))**2)

374

In [327]:
(1 / len(x)) * sum((y - x.dot(beta_new))**2)

93.5

In [317]:
sum((y - x.dot(beta_new))**2) / 4

93.5

In [328]:
lam * (sum(abs(beta_new)))

6

In [318]:
sum(abs(beta_new))

6

In [320]:
93.5+(2*6)

105.5

In [322]:
sum(abs(beta_new)) * 2

12

In [323]:
93.5 + 12

105.5

In [324]:
1 / len(x)

0.25

In [329]:
93.5+6

99.5

In [330]:
beta_new = np.array([1,-2,3])

In [331]:
x.dot(beta_new)

array([11, 17,  8, 10])

In [332]:
y - x.dot(beta_new)

array([ -9, -14,  -8, -11])

In [333]:
(y - x.dot(beta_new))**2

array([ 81, 196,  64, 121])

In [335]:
sum((y - x.dot(beta_new))**2)

462

In [336]:
(1/len(x)) * sum((y - x.dot(beta_new))**2)

115.5

In [337]:
462/4

115.5

In [338]:
(sum(abs(beta_new)))

6

In [339]:
6*2 + 115.5

127.5