In [1]:
import numpy as np
import pandas as pd
#from sklearn import preprocessing
import matplotlib.pyplot as plt
import seaborn as sns
#from IPython.core.debugger import Tracer
#import scipy as sp

from pylab import rcParams
rcParams['figure.figsize'] = 5, 8

%matplotlib inline

# Exercise One

In [5]:
y = np.array([2,3,0-1])
x = np.array([4,-2,1,
              5,-3,2,
              1,1,3,
              0,1,4]).reshape(4,3)
lam = 1
beta = np.zeros(3)

In [6]:
x

array([[ 4, -2,  1],
       [ 5, -3,  2],
       [ 1,  1,  3],
       [ 0,  1,  4]])

In [13]:
x[:,0:3]

array([[ 4, -2,  1],
       [ 5, -3,  2],
       [ 1,  1,  3],
       [ 0,  1,  4]])

In [14]:
x[:, (0,2)]

array([[4, 1],
       [5, 2],
       [1, 3],
       [0, 4]])

In [15]:
x[:, (0,1,2)]

array([[ 4, -2,  1],
       [ 5, -3,  2],
       [ 1,  1,  3],
       [ 0,  1,  4]])

In [19]:
x[:, [0,2]]

array([[4, 1],
       [5, 2],
       [1, 3],
       [0, 4]])

In [20]:
np.arange()