In [2]:
# general
import numpy as np
import pandas as pd
from IPython.display import display
import importlib

# first used in exercise one
import kernelsvm as svm
from sklearn.metrics.pairwise import linear_kernel, polynomial_kernel
from sklearn.datasets import fetch_mldata
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [3]:
importlib.reload(svm)

<module 'kernelsvm' from '/Users/andrewenfield/work/github/Data558/Week09/kernelsvm.py'>

In [4]:
x_simple = np.array([3,2,0,1,-1,-2]).reshape(3,2)
x_simple

array([[ 3,  2],
       [ 0,  1],
       [-1, -2]])

Note: Per the request in the "Collaboration policy" note, I've discussed at least part of this assignment with many of the MS employees in the class, including Abhishek, Geoff, Suman, and Charles. (Different weeks/different assignments have different people, depending upon who attends our study groups, but I'll probably just include this blurb w/ each homework since it's generally correct.) I've also gotten input from the discussion board.

# Exercise one

_Compute the gradient ∇F(α) of F.

_Write a function computegram that computes, for any set of datapoints x1, . . . , xn, the kernel matrix K._

I implemented the computegram_linear function, and all of the supporting functions including the gradient and objective functions, in the file kernelsvm.py, which I imported into this notebook with the alias svm. I also include my (relatively minimal) unit tests, in linearsvm-test.py.

In [5]:
svm.computegram_linear(x_simple)

array([[13,  2, -7],
       [ 2,  1, -2],
       [-7, -2,  5]])

In [6]:
svm.computegram_polynomial(x_simple, 2, 1)

array([[196,   9,  36],
       [  9,   4,   1],
       [ 36,   1,  36]])

_Write a function kerneleval that computes, for any set of datapoints x1, . . . , xn and a new datapoint x⋆, the vector of kernel evaluations [k(x1, x⋆), . . . , k(xn, x⋆)]T._

My understanding here is that I'm not using the kernel matrix - that is, the reference to 'kernel evaluation' means to use the kernel _function_, not the kernel matrix. I think this is just (part of - since no alpha weighting yet) the predict step, which - for a linear kernel - is the sum of the inner products between each observation and the value to be predicted, weighted by each learned value of alpha.

In [7]:
svm.kerneleval_linear(x_simple, np.array([2,2]))

array([10,  2, -6])

**TODO** Is there a way this function should be generalized to work with different kinds of kernels?

_Consider the MNIST dataset. You can find instructions on how to download it here: http://scikit-learn.org/stable/datasets/mldata.html. Pick two classes of your choice. Your are going to work on the dataset consisting of the data from these two classes. Standardize the data, if you have not done so already._

In [8]:
mnist = fetch_mldata('MNIST original')
mnist.data.shape, mnist.target.shape

((70000, 784), (70000,))

We'll use 1 and 8. 

In [9]:
ones_and_eights = (mnist.target == 1) | (mnist.target == 8)
X = mnist.data[ones_and_eights]
y = mnist.target[ones_and_eights]
X.shape, y.shape, np.unique(y)

((14702, 784), (14702,), array([ 1.,  8.]))

In [10]:
X_scaled = preprocessing.scale(X)
X_scaled.shape

/Users/andrewenfield/miniconda3/envs/data558/lib/python3.6/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype uint8 was converted to float64 by the scale function.
  warnings.warn(msg, _DataConversionWarning)


(14702, 784)

In [11]:
X_scaled_train, X_scaled_test, y_train, y_test = train_test_split(X_scaled, y)
X_scaled_train.shape, X_scaled_test.shape, y_train.shape, y_test.shape

((11026, 784), (3676, 784), (11026,), (3676,))

_Write a function mysvm that implements the fast gradient algorithm to train the kernel support vector machine with the squared hinge loss. The function takes as input the initial step-size value for the backtracking rule and a maximum number of iterations._

As noted above, I implemented this in the kernelsvm.py file. Instead of creating a function named mysvm, I just call my fastgradalgo function and pass in references to the kernel SVM gradient and objective functions (which are also implemented in the same file).

_Train your kernel support vector machine with the squared hinge loss and the polyno- mial kernel of order 7 on the the MNIST dataset, tuning the regularization parameter λ using cross-validation._

In [11]:
importlib.reload(svm)

<module 'kernelsvm' from '/Users/andrewenfield/work/github/Data558/Week09/kernelsvm.py'>

In [12]:
t_init = 0.01
max_iters = 10

In [14]:
results = svm.fastgradalgo(
    svm.computegram_linear(X_scaled_train), y_train, t_init=t_init, 
    grad_func = svm.compute_kernelsvm_gradient, 
    obj_func = svm.compute_kernelsvm_objective, 
    lam=1, max_iter=max_iters, t_func=svm.backtracking)
results[-3:]

0             1             2             3             4      \
8   1.962679e-07 -3.714314e-07 -3.599574e-07  6.254346e-08 -1.937236e-07   
9   2.006736e-07 -3.920476e-07 -3.829207e-07  1.686493e-08 -2.112396e-07   
10  2.123096e-07 -4.200657e-07 -4.202606e-07  1.445931e-08 -2.363714e-07   

           5             6             7             8             9      \
8   1.196436e-07 -2.794986e-07  2.249385e-07  1.222759e-07 -1.317698e-07   
9   1.306675e-07 -2.874655e-07  2.055603e-07  1.441291e-07 -1.480287e-07   
10  1.612193e-07 -3.029186e-07  1.933410e-07  1.622444e-07 -1.680080e-07   

        ...              11016         11017         11018         11019  \
8       ...       1.797507e-07 -3.081618e-07 -1.392155e-07 -2.482354e-07   
9       ...       1.883978e-07 -3.181666e-07 -1.389441e-07 -2.468098e-07   
10      ...       1.936730e-07 -3.355555e-07 -1.487826e-07 -2.600592e-07   

           11020         11021         11022         11023         11024  \
8  -1.926423e-07  4.772608e-08  8.568301e-08  7.770417e-08 -2.091966e-07   
9  -1.849821e-07  8.132389e-08  3.805241e-08  7.846875e-08 -2.128476e-07   
10 -1.892138e-07  1.036008e-07 -2.630979e-08  9.976332e-08 -2.299417e-07   

           11025  
8  -2.811912e-07  
9  -2.880118e-07  
10 -3.118412e-07  

[3 rows x 11026 columns]

_Compare the performance of kernel SVMs with different kernels (polynomial kernels with different orders, Gaussian RBF with different bandwidths, etc.)._